version: '3.1'

services:
  disease-svc:
    container_name: disease_svc
    build: ./
    environment:
      EUREKA_HOST: eureka-server
      EUREKA_PORT: 8761
      PG_HOST: disease_svc_db
      PG_USER: postgres
      PG_PASS: marek123
      PG_PORT: 5432
      PG_DB: postgres
      DISEASE_SVC_PORT: 8080
    ports:
      - 8080:8080
    networks:
      - nkm
      - postgres
    depends_on:
      - pgdb

  pgdb:
    container_name: disease_svc_db
    hostname: disease_svc_db
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: marek123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - postgres
      
networks:
  nkm:
    external:
      name: nemocnice-network
  postgres:
    driver: bridge
